export const state = {
  deckTab: 'list',
  deckQuery: '',
  deckSort: 'rank',
  deckDir: 'asc',
  dashboardMetaFilter: 'overall',
  dashboardMetaSort: 'winRate',
  dashboardPartyFilter: '전체',
  guideTab: 'traits',
  guideQuery: '',
  guidePage: 1,
  guideCost: 'all',
  favorites: [],
  partyFilter: '전체',
  partyQuery: '',
  partyActiveRoom: '일반',
  partyJoinedId: null,
  patchCategory: '전체',
  patchType: '전체 변경',
  patchQuery: '',
  patchHighOnly: false,
  patchPage: 1,
  patchVersion: '17.3',
  expandedPatch: [],
  expandedMatch: null,
  visibleMatches: 10,
}
