package com.tftgogo.domain.community.repository;

import com.tftgogo.domain.community.entity.PartyApplicationStatus;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.jdbc.Sql;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.datasource.url=jdbc:h2:mem:party-active-query-test;MODE=MySQL;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.flyway.enabled=false"
})
@Sql(statements = {
        "drop table if exists party_applications",
        "drop table if exists party_posts",
        """
        create table party_posts (
            id bigint generated by default as identity primary key,
            user_id bigint not null,
            title varchar(200) not null,
            content text not null,
            game_mode varchar(30),
            max_members int not null,
            current_members int not null,
            deadline timestamp,
            is_closed boolean not null,
            created_at timestamp not null,
            updated_at timestamp not null,
            deleted_at timestamp
        );
        """,
        """
        create table party_applications (
            id bigint generated by default as identity primary key,
            party_post_id bigint not null,
            user_id bigint not null,
            status varchar(20) not null,
            created_at timestamp not null,
            message text,
            responded_at timestamp,
            constraint fk_party_application_post
                foreign key (party_post_id) references party_posts(id)
        );
        """,
        """
        insert into party_posts (
            id, user_id, title, content, max_members, current_members,
            deadline, is_closed, created_at, updated_at, deleted_at
        ) values
            (1, 101, '모집 마감 파티', '정원 마감', 4, 4,
             '2026-07-17 12:00:00', true, '2026-07-16 09:00:00', '2026-07-16 09:00:00', null),
            (2, 102, '기한 없는 모집 마감 파티', '정원 마감', 4, 4,
             null, true, '2026-07-16 09:00:00', '2026-07-16 09:00:00', null),
            (3, 103, '기한 만료 파티', '기한 만료', 4, 2,
             '2026-07-15 12:00:00', true, '2026-07-15 09:00:00', '2026-07-15 09:00:00', null),
            (4, 104, '삭제된 파티', '삭제됨', 4, 2,
             '2026-07-17 12:00:00', false, '2026-07-16 09:00:00', '2026-07-16 09:00:00',
             '2026-07-16 10:00:00');
        """,
        """
        insert into party_applications (
            id, party_post_id, user_id, status, created_at, responded_at
        ) values
            (1, 1, 201, 'ACCEPTED', '2026-07-16 09:30:00', '2026-07-16 09:30:00'),
            (2, 2, 202, 'ACCEPTED', '2026-07-16 09:30:00', '2026-07-16 09:30:00'),
            (3, 3, 203, 'ACCEPTED', '2026-07-15 09:30:00', '2026-07-15 09:30:00'),
            (4, 4, 204, 'ACCEPTED', '2026-07-16 09:30:00', '2026-07-16 09:30:00');
        """
})
class PartyActiveQueryContractTest {

    private static final LocalDateTime NOW = LocalDateTime.of(2026, 7, 16, 12, 0);

    private final PartyApplicationRepository partyApplicationRepository;
    private final PartyPostRepository partyPostRepository;

    @Autowired
    PartyActiveQueryContractTest(
            PartyApplicationRepository partyApplicationRepository,
            PartyPostRepository partyPostRepository
    ) {
        this.partyApplicationRepository = partyApplicationRepository;
        this.partyPostRepository = partyPostRepository;
    }

    @Test
    void 모집이_마감됐어도_기한이_남은_파티는_활성으로_조회한다() {
        // given
        Long ownerId = 101L;
        Long applicantId = 201L;

        // when
        boolean hasOwnedParty = partyPostRepository.existsActiveOwnedPartyPost(ownerId, NOW);
        boolean hasOtherOwnedParty =
                partyPostRepository.existsActiveOwnedPartyPostForOtherParty(ownerId, 99L, NOW);
        boolean hasAcceptedParty = partyApplicationRepository.existsActiveAcceptedApplication(
                applicantId,
                PartyApplicationStatus.ACCEPTED,
                NOW
        );
        boolean hasOtherAcceptedParty =
                partyApplicationRepository.existsActiveAcceptedApplicationForOtherParty(
                        applicantId,
                        PartyApplicationStatus.ACCEPTED,
                        99L,
                        NOW
                );
        boolean hasExcludedOwnedParty =
                partyPostRepository.existsActiveOwnedPartyPostForOtherParty(ownerId, 1L, NOW);
        boolean hasExcludedAcceptedParty =
                partyApplicationRepository.existsActiveAcceptedApplicationForOtherParty(
                        applicantId,
                        PartyApplicationStatus.ACCEPTED,
                        1L,
                        NOW
                );

        // then
        assertThat(hasOwnedParty).isTrue();
        assertThat(hasOtherOwnedParty).isTrue();
        assertThat(hasAcceptedParty).isTrue();
        assertThat(hasOtherAcceptedParty).isTrue();
        assertThat(hasExcludedOwnedParty).isFalse();
        assertThat(hasExcludedAcceptedParty).isFalse();
    }

    @Test
    void 기한이_없고_모집이_마감된_파티도_활성으로_조회한다() {
        // given
        Long ownerId = 102L;
        Long applicantId = 202L;

        // when
        boolean hasOwnedParty = partyPostRepository.existsActiveOwnedPartyPost(ownerId, NOW);
        boolean hasAcceptedParty = partyApplicationRepository.existsActiveAcceptedApplication(
                applicantId,
                PartyApplicationStatus.ACCEPTED,
                NOW
        );

        // then
        assertThat(hasOwnedParty).isTrue();
        assertThat(hasAcceptedParty).isTrue();
    }

    @Test
    void 기한이_만료되거나_삭제된_파티는_활성으로_조회하지_않는다() {
        // given
        Long expiredOwnerId = 103L;
        Long deletedOwnerId = 104L;
        Long expiredApplicantId = 203L;
        Long deletedApplicantId = 204L;

        // when
        boolean hasExpiredOwnedParty =
                partyPostRepository.existsActiveOwnedPartyPost(expiredOwnerId, NOW);
        boolean hasDeletedOwnedParty =
                partyPostRepository.existsActiveOwnedPartyPost(deletedOwnerId, NOW);
        boolean hasExpiredAcceptedParty =
                partyApplicationRepository.existsActiveAcceptedApplication(
                        expiredApplicantId,
                        PartyApplicationStatus.ACCEPTED,
                        NOW
                );
        boolean hasDeletedAcceptedParty =
                partyApplicationRepository.existsActiveAcceptedApplication(
                        deletedApplicantId,
                        PartyApplicationStatus.ACCEPTED,
                        NOW
                );

        // then
        assertThat(hasExpiredOwnedParty).isFalse();
        assertThat(hasDeletedOwnedParty).isFalse();
        assertThat(hasExpiredAcceptedParty).isFalse();
        assertThat(hasDeletedAcceptedParty).isFalse();
    }
}
